version: '3.9'
services:
  violence_model:
    build: ./models/violence
    ports:
      - "8001:80"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  hate_model:
    build: ./models/hate
    ports:
      - "8002:80"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  spam_model:
    build: ./models/spam
    ports:
      - "8003:80"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
